CREATE TABLE KHOA 
(
    MAKHOA VARCHAR(4) PRIMARY KEY,
    TENKHOA VARCHAR(40),
    NGTLAP DATETIME, 
    TRGKHOA CHAR(4)
)
GO
CREATE TABLE MONHOC
(
    MAMH VARCHAR (10) PRIMARY KEY,
    TENMH VARCHAR (40),
    TCLT TINYINT,
    TCTH TINYINT,
    MAKHOA VARCHAR(4)
)
GO 
-- KHOA NGOAI 
ALTER TABLE MONHOC ADD CONSTRAINT FK_MAKHOA FOREIGN KEY (MAKHOA) REFERENCES dbo.KHOA(MAKHOA)

GO
CREATE TABLE DIEUKHIEN 
(
    MAMH VARCHAR(10) NOT NULL,
    MAMH_TRUOC VARCHAR(10) NOT NULL,
    PRIMARY KEY (MAMH, MAMH_TRUOC)

)
GO
ALTER TABLE DIEUKHIEN ADD CONSTRAINT FK_MAMH FOREIGN KEY (MAMH) REFERENCES dbo.MONHOC(MAMH)
GO
ALTER TABLE DIEUKHIEN ADD CONSTRAINT FK_MAMH_TRUOC FOREIGN KEY (MAMH_TRUOC) REFERENCES dbo.MONHOC(MAMH)
GO 

CREATE TABLE GIAOVIEN
(
    MAGV CHAR(4) PRIMARY KEY,
    HOTEN VARCHAR(40),
    HOCVI VARCHAR (10),
    HOCHAM  VARCHAR (10),
    GIOITINH VARCHAR(3),
    NGSINH DATETIME,
    NGVL DATETIME,
    HESO NUMERIC(4,2),
    MUCLUONG MONEY,
    MAKHOA VARCHAR(4)
)
GO
ALTER TABLE GIAOVIEN ADD CONSTRAINT KT_GIOITINH CHECK (GIOITINH IN ('NAM', 'NU'))
GO
ALTER TABLE GIAOVIEN ADD CONSTRAINT FK_MAKHOA1 FOREIGN KEY (MAKHOA) REFERENCES dbo.KHOA(MAKHOA)
GO
ALTER TABLE GIAOVIEN ADD CONSTRAINT KT_HOCVI CHECK (HOCVI IN ('CN', 'KS', 'ThS', 'TS', 'PTS'))
GO
CREATE TABLE LOP 
(
    MALOP CHAR(3) PRIMARY KEY,
    TENLOP VARCHAR(40),
    TRGLOP CHAR(5),
    SISO TINYINT,
    MAGVCN CHAR(4)
)
GO
ALTER TABLE LOP ADD CONSTRAINT KH_MAGVCN FOREIGN KEY (MAGVCN) REFERENCES dbo.GIAOVIEN(MAGV)
GO

CREATE TABLE HOCVIEN 
(
    MAHV CHAR (5) PRIMARY KEY,
    HO VARCHAR (40),
    TEN VARCHAR (10),
    NGSINH DATETIME,
    GIOITINH VARCHAR (3),
    NOISINH VARCHAR(40),
    MALOP CHAR(3)
)
GO
ALTER TABLE HOCVIEN ADD CONSTRAINT KT_GIOITINH2 CHECK (GIOITINH IN ('NAM', 'NU'))
GO
-- KHOA NGOAI

ALTER TABLE HOCVIEN ADD CONSTRAINT FK_MALOP3 FOREIGN KEY (MALOP) REFERENCES dbo.LOP(MALOP)

GO
CREATE TABLE GIANGDAY (
    MALOP CHAR(3) NOT NULL,
    MAMH VARCHAR(10) NOT NULL,
    MAGV CHAR(4),
    HOCKY TINYINT,
    NAM SMALLINT,
    TUNGAY DATETIME,
    DENNGAY DATETIME,
    PRIMARY KEY (MALOP, MAMH)
)
GO 
ALTER TABLE GIANGDAY ADD CONSTRAINT FK_MALOP4 FOREIGN KEY (MALOP) REFERENCES dbo.LOP(MALOP)
GO
ALTER TABLE GIANGDAY ADD CONSTRAINT FK_MAMH5 FOREIGN KEY (MAMH) REFERENCES dbo.MONHOC(MAMH)
GO
CREATE TABLE KETQUATHI 
(
    MAHV CHAR(5) NOT NULL,
    MAMH VARCHAR(10) NOT NULL,
    LANTHI TINYINT NOT NULL,
    NGTHI DATETIME,
    DIEM NUMERIC(4,2),
    KQUA VARCHAR(10),
    PRIMARY KEY (MAHV,MAMH, LANTHI)
)
GO 
ALTER TABLE KETQUATHI ADD CONSTRAINT FK_MAHV6 FOREIGN KEY (MAHV) REFERENCES dbo.HOCVIEN(MAHV)
GO 
ALTER TABLE KETQUATHI ADD CONSTRAINT FK_MAMH7 FOREIGN KEY (MAMH) REFERENCES dbo.MONHOC(MAMH)
GO
ALTER TABLE KETQUATHI ADD CONSTRAINT KT_DIEM8 CHECK (DIEM BETWEEN 0 AND 10)
GO

CREATE TRIGGER CHECK_KQUA
ON KETQUATHI
AFTER INSERT, UPDATE
AS 
BEGIN 
    UPDATE KETQUATHI
    SET KQUA = CASE 
                 WHEN DIEM >= 5 THEN 'Dat'
                 ELSE 'Khong dat'
               END
    FROM INSERTED i
    WHERE KETQUATHI.MAHV = i.MAHV
      AND KETQUATHI.MAMH = i.MAMH
      AND KETQUATHI.LANTHI = i.LANTHI;
END
GO

ALTER TABLE KETQUATHI
ADD CONSTRAINT KT_LANTHI10 CHECK (LANTHI BETWEEN 1 AND 3)
GO
ALTER TABLE KETQUATHI
ADD CONSTRAINT KT_HOCKI11 CHECK (LANTHI BETWEEN 1 AND 3)
GO
