
create table KHACHHANG 
(
    MAKH CHAR (4) PRIMARY KEY,
    HOTEN VARCHAR (40),
    DCHI VARCHAR (50),
    SODT VARCHAR (20),
    NGSINH DATETIME,
    NGDKY DATETIME,
    DOANHSO MONEY
)
GO
ALTER TABLE KHACHHANG ADD CONSTRAINT CON_KTRA CHECK (NGDKY > NGSINH)

ALTER TABLE KHACHHANG ADD LOAIKH TINYINT
GO
ALTER TABLE KHACHHANG ADD ID_LOAIKH VARCHAR(20)
GO
alter table KHACHHANG alter COLUMN ID_LOAIKH TINYINT 
GO
ALTER TABLE KHACHHANG 
ADD CONSTRAINT FK_LOAIKH FOREIGN KEY (ID_LOAIKH) REFERENCES dbo.LOAIKH(ID_LOAIKH);
GO


CREATE TABLE NHANVIEN
(
    MANV CHAR(4) PRIMARY KEY,
    HOTEN VARCHAR (40),
    SODT VARCHAR(20),
    NGVL DATETIME
)
GO

CREATE TABLE SANPHAM  
(
    MASP CHAR (4) PRIMARY KEY,
    TENSP VARCHAR (40),
    DVT VARCHAR (20),
    NUOCSX VARCHAR (40),
    GIA MONEY

)
ALTER TABLE SANPHAM ADD GHICHU VARCHAR (20)
GO
ALTER TABLE SANPHAM ALTER COLUMN GHICHU VARCHAR (100)
GO
ALTER TABLE SANPHAM DROP COLUMN GHICHU
GO

ALTER TABLE SANPHAM ADD CONSTRAINT CON_DVT CHECK (DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'))
GO

ALTER TABLE SANPHAM ADD CONSTRAINT CON_GIA CHECK (GIA >= 500)
CREATE TABLE HOADON 
(
    SOHD INT PRIMARY KEY,
    NGHD DATETIME,
    MAKH CHAR(4),
    MANV CHAR(4),
    TRIGIA MONEY,
    FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG (MAKH)
)
GO

CREATE TABLE CTHD 
(
    SOHD INT NOT NULL,
    MASP CHAR(4) NOT NULL,
    SL INT,
    PRIMARY KEY (SOHD, MASP),
    FOREIGN KEY (SOHD) REFERENCES dbo.HOADON (SOHD),
    FOREIGN KEY (MASP) REFERENCES dbo.SANPHAM (MASP)

)
ALTER TABLE CTHD ADD CONSTRAINT CON_SL CHECK (SL >= 1)

CREATE TABLE LOAIKH
(
    ID_LOAIKH TINYINT PRIMARY KEY,
    LOAIKH VARCHAR (20)
)
INSERT INTO LOAIKH ( ID_LOAIKH, LOAIKH ) 
VALUES (1, N'Vang lai'), 
       (2, N'Thuong xuyen'), 
       (3, N'VIP')

